language: php

sudo: false

git:
    depth: 1

matrix:
    include:
        - php: 5.6

script:
    - echo "script section"

branches:
    only:
        - master

deploy:
    provider: script
    script: echo "deploy section"
    on:
        branch:
            master
